Stylowanie i rozwijanie komponentów, dodanie palety kolorów
krzysztofsaja/cthulu pull request #12
Opened 2023-11-20 16:37 UTC by Nekares

Wystylowałem komponenty tj. CharacterPic, TopBar, IntroHeader. Stworzyłem plik cssowy, w którym zrobiłem wspomniane stylowania oraz ustawiłem je na sztywno w odpowiednich miejscach w aplikacji. Dodałem również paletę kolorów do global.css. Aplikacja włącza się bez problemów i aktualnie wygląda tak:

https://www.loom.com/share/3118f9c2d3c140ac966666f62f20bb1f?sid=36c62766-01c3-495b-bfed-063f9859d37c

2023-11-21 18:36 UTC, julwlodarczyk approved these changes
Aplikacja działa, występują błędy w kodzie, które są wskazywane przez VisualStudio. Nie znam do końca ich podłoża, ale nie wydaje mi się żeby wpływały na działanie aplikacji na tym etapie kodu.

2023-11-21 18:57 UTC, julwlodarczyk requested changes
Aplikacja działa, występują błędy w kodzie, które są wskazywane przez VisualStudio. Nie znam do końca ich podłoża, ale nie wydaje mi się żeby wpływały na działanie aplikacji na tym etapie kodu. Wydaje mi się tylko, że te elementy powinny mieć swoje docelowe miejsce. Jak weszłam w Twój branch i odpaliłam aplikację to po późniejszym poruszaniu się w aplikacji zniknęły mi Twoje zmiany. Myślę, że to jest do poprawienia i wspólnego omówienia.

2023-11-22 09:40 UTC, nelalasinska approved these changes

2023-11-22 11:29 UTC, krzysztofsaja commented on src/shared/components/CharacterPic.tsx
> +    <div className="!absolute !left-[232px] !top-[63px]">
Hm... This is not good patter for CSS applying. Is it RWD? Why 232px from left? Why not use grid or flexbox for all of it. We should avoid absloute and importants (!)

2023-11-22 11:30 UTC, krzysztofsaja requested changes

2023-11-22 11:30 UTC, krzysztofsaja commented on src/shared/components/TopBar.tsx
> +    <div className="relative w-[375px] h-[40px] bg-primarydark">
We should not style using pixels. We need use RWD. Please read about it in W3Schools (RWD). Use flexbox / grid

2023-12-17 17:41 UTC, closed without merging