Characteristics passive
krzysztofsaja/cthulu pull request #24
Opened 2023-12-20 15:02 UTC by haghaata

Dodanie charasteristics passive do formularza

![image](https://github.com/krzysztofsaja/cthulu/assets/127862443/753df322-d864-4aa3-8b74-5e1c4ef3ccbb)

2023-12-20 16:57 UTC, Fyredale approved these changes

2023-12-21 07:37 UTC, krzysztofsaja requested changes

2023-12-21 07:37 UTC, krzysztofsaja commented on src/shared/components/character-form.tsx
> +    let collContent = document.querySelector('.coll-content');
Pisząc w reakcie, nie musimy (i jest to złą praktyką), nie łapać elementów przez document.querySelector. Możemy bezpośrednio manipulować klasami lub stylem (proszę sprawdzić dokumentację)

2023-12-21 07:38 UTC, krzysztofsaja requested changes

2023-12-21 07:38 UTC, krzysztofsaja commented on src/shared/components/character-form.tsx
> +        <div
Klikalne elementy powinny być przyciskami "button"

2023-12-21 07:41 UTC, krzysztofsaja requested changes

2023-12-21 07:41 UTC, krzysztofsaja commented on src/shared/components/character-form.tsx
> +    let collContent = document.querySelector('.coll-content');
Najlepszym rozwiązaniem stylowania jest dynamiczne dodawania / usuwanie klas tailwind css

2023-12-21 13:43 UTC, haghaata commented
zaktualizowałam brancha, uprzejmie proszę o sprawdzenie

2024-01-18 07:57 UTC, krzysztofsaja approved these changes

2024-01-21 09:39 UTC, merged