Hook form zuzia tutel
krzysztofsaja/cthulu pull request #6
Opened 2023-11-15 17:30 UTC by rakzuz

2023-11-20 16:50 UTC, krzysztofsaja requested changes

2023-11-20 16:50 UTC, krzysztofsaja commented on moja-aplikacja/src/Form.js
> +
1. Plik powinien mieć rozszerzenie tsx.
2. Proszę umieścić go w innym folderze, nie "moja-aplikacja". 
3. Proszę zmienić mu nazwę na coś bardziej sensownego. Formularzy może być wiele. Jakie tot jest formularz?
4. Należy użyć go w odpowiednim widoku, zaraz sprawdzę w którym

2023-11-20 16:51 UTC, krzysztofsaja commented on moja-aplikacja/src/Form.js
> +
Ten komponent należy użyć tutaj:
<img width="1714" alt="image" src="https://github.com/krzysztofsaja/cthulu/assets/1513235/21885a17-781a-4a90-959b-87ec6523a447">

Można go też umieścić tymczasowo w folderze związanym z tą stroną

2023-11-21 09:46 UTC, rakzuz commented
![image](https://github.com/krzysztofsaja/cthulu/assets/127862448/a9dfb27f-db3a-420e-88b6-3aed1d2b6b6b)

2023-11-21 10:35 UTC, rakzuz commented
https://github.com/krzysztofsaja/cthulu/assets/127862448/96cb0992-3126-421a-b934-e71b479e7266

2023-11-22 11:35 UTC, krzysztofsaja reviewed
Proszę pokazać na wideo, że wszystko działa. Dobrze byłoby też przenieść koponent "character-form" do osobnego folderu "components".

2023-11-23 07:41 UTC, krzysztofsaja approved these changes

2023-11-23 07:43 UTC, merged